### ISSUE TITLE
plugin goes down sometimes

### ISSUE THREAD

**Issue by armandoi75** [oznu/homebridge-gsh#23]
Hi, 
sometime in a day if I ask google to operate on the homebridge plugin, sometime it answer "sorry homebridge is not responding". So I check on the homekit app and homebridge is on and working. Do you have any suggestion? 
Second question, is it possible to link a second account on the plugin? This because if a second voice ask to do some action the ACL block it.

Thanks in advance

**Comment by oznu** [comment]
Hi @armandoi75,

Send me an email (address in profile) with the username/email you used to link Homebridge and I'll take a look at the logs to see if anything stands out.

Regarding the additional account, that's not possible at this stage without setting up a second Homebridge instance - would inviting the other user account to the home via the Google Home app allow them to control the accessories?

**Comment by armandoi75** [comment]
Hi, I answered you by mail ;-)

**Comment by oznu** [comment]
Hi @armandoi75,

I've checked out the logs since the 12th of December when it looks like you connected you replaced the Google account connection with the GitHub connection as you described in your email.

I can see your connection to the GSH servers is stable as well, with just the one disconnect/reconnect since the 12th of December a few hours ago when you must have restarted Homebridge.

During this time I have only found one EXECUTE request timeout, which occurs when Homebridge does not respond to a request within 10 seconds. This could be because Homebridge missed the command, or it took Homebridge more than 10 seconds to process the request.

Dec 14 00:50:22 - Request Sent to "Turn On" multiple devices
Dec 14 00:50:32 - Request Timed Out

Do you remember if the command actually succeeded when Google responded with "homebridge is not responding" on this occasion?

I did make some changes about a week ago based on the feedback from another user, that fixed a server side bug that caused "not responding" issues - that user has since confirmed the issue no longer is present. The timeout you experienced above was not related to this. Apart from the one issue on Dec 14, have you had any other occurrences of this issue in the last few days?

_**Note 1:** All dates and times are GMT+11._

_**Note 2:** The Homebridge GSH server logs contain no personal information, usernames or email addresses, only a unique identifier from AUTH0. Logs are discarded within 5-7 days depending on traffic volume._

**Comment by armandoi75** [comment]
Hi, as always, thanks for your fast answer.

"Dec 14 00:50:22 - Request Sent to "Turn On" multiple devices

Dec 14 00:50:32 - Request Timed Out

Do you remember if the command actually succeeded when Google responded with "homebridge is not responding" on this occasion?"

**Yes** the answer was exactly homebridge is not responding.

"Apart from the one issue on Dec 14, have you had any other occurrences of this issue in the last few days?"
**No** , in the last few days the problem seems to be disappeared. As I told you I also changed the account switching from google account to github account.
