### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rmoya87** [oznu/homebridge-gsh#3]
Hi i tryed install it, but display this error:

npm ERR! Linux 4.19.58-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-gsh"
npm ERR! node v10.15.2
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56' -> '/usr/lib/node_modules/homebridge-gsh/node_modules/@oznu/ws-connect'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56' -> '/usr/lib/node_modules/homebridge-gsh/node_modules/@oznu/ws-connect'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
npm ERR! code 1
pi@raspberrypi:~ $ sudo npm install -g homebridge-gsh
/usr/lib
└── (empty)

npm ERR! Linux 4.19.58-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "homebridge-gsh"
npm ERR! node v10.15.2
npm ERR! npm  v3.10.10
npm ERR! path /usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56' -> '/usr/lib/node_modules/homebridge-gsh/node_modules/@oznu/ws-connect'
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/@oznu/ws-connect-f59aab56' -> '/usr/lib/node_modules/homebridge-gsh/node_modules/@oznu/ws-connect'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
npm ERR! code 1

**Comment by oznu** [comment]
Hi @rmoya87,

Thanks for your interest in this plugin. 

Please note that as per the notice here https://github.com/oznu/homebridge-gsh/issues/2 and the "Work In Progress" message on the repo page, this plugin is still not ready for general users - you won't be able to connect your Google Home app to the service yet (it's still pending a review from Google!) 

In regards to the error you have, it is caused by your npm version is out-of-date. The logs show you have npm 3.10.10 while the current version shipping with Node.js v10 is 6.9.0.

Npm 3.x does not support scoped packages properly, such as `@oznu/ws-connect` which is why you're seeing this error. Fix up your npm version and the issue will go away.
